### ISSUE TITLE
2nd Deliverable - Self Report

### ISSUE THREAD

**Issue by UO276188** [Arquisoft/lomap_en1b#58]
For this deliverable I have worked on the webapp:
- Home page and Login view (#54 #51) with the PODS 
- Map view adding markers (#55 #49) 

In both of my contributions I've been working together with @uo277412 .

**Comment by silSuarezP** [comment]
For this deliverable I have worked on the webapp:

- Home page and Login view (Login Interface and Home Page  #54 https://github.com/Arquisoft/lomap_en1b/issues/51) with the PODS
- Map view adding markers (Map with markers  #55 https://github.com/Arquisoft/lomap_en1b/issues/49)

In both of my contributions I've been working together with @UO276188  .

**Comment by UO278249** [comment]
For this deliverable I have worked on the map view in the webapp (#57 https://github.com/Arquisoft/lomap_en1b/issues/49)

**Comment by uo276670** [comment]
For this deliverable I have worked on:
- RestAPI access component on issue ( #36 )
- Map View with markers ( #49 )
- First small fix of the documentation ( #59  ) 

The final connection of the webbapp and the restapi was made possible thanks to the help of @Elias-Llera

**Comment by MarioP-Dev** [comment]
For this deliverable I have worked on the connection webapp-restapi:
- Initialize and configure the React + Redux Toolkit project in [this commit](https://github.com/Arquisoft/lomap_en1b/commit/7605ea5ae00d35c9f62717d3f2b349e63c1fed81)
- Authentication with Redux then replaced by fetch API due to problem with multiple requests (easier in vanilla JS than in redux)
- @Elias-Llera and I work together to solve problems with authentication with SOLID Pods

**Comment by Elias-Llera** [comment]
For this deliverable I have worked on:

* RestAPI development
	* Base configuration
	* Developed authentication service for SOLID PODs #51 
	* Worked on authenticated fetches after user is logged in #52 
	* Developed locations service #60
		* Location service itself
		* Builders
		* Validators
* Helped out with connection of the webapp with the RestAPI #36
