### ISSUE TITLE
UI/UX Improval: Login form

### ISSUE THREAD

**Issue by MarioP-Dev** [Arquisoft/lomap_en1b#61]
In order to improve the customer's interaction, in the login process, it's better to directly call the login function when using the provided Pod providers and not to replace que input field with the provider's login URL as a user would be confused because it's asked to decide to use the provider URL **or** use the provided ones but, in the end, the user need to use the input field in order to correctly login.

![Captura de pantalla 2023-03-13 114840](https://user-images.githubusercontent.com/40372021/224681089-e93a34f4-6769-4b56-95e2-11a4045830ff.png)

![Captura de pantalla 2023-03-13 114917](https://user-images.githubusercontent.com/40372021/224681110-b1797d7b-7a9a-462b-845e-576415e7b0c8.png)

**Comment by UO276188** [comment]
We have a problem here. We tried to fix that and the property which stores the providerValue changes but it does not redirect to the provider page.
The thing is:
The button is like that, in which the onClick calls to handleButton passing as a parameter the url of the provider.
'<Button onClick={() => handleButton("https://inrupt.net/login") }> Inrupt </Button>'

And....
    const [providerValue, setProviderValue] = useState('');
 
    const handleLogin =  () => {
      var url : string = providerValue + "";
      window.location.replace(url)
    };

    const handleButton = (prov: SetStateAction<string>)=>{
      setProviderValue(prov)
      handleLogin() 
    }


I have to mention that the LogIn button uses handleLogin in the following way:
`<Button onClick={handleLogin}> Log in  </Button>`

I can't find the problem here :(

Also, the code is in the branch login-sara-sil, in webapp/src/components/Login.tsx

**Comment by UO276188** [comment]
@MarioP-Dev helped and merged #76 .
