### ISSUE TITLE
Implement locations filter in redux cache

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/lomap_en1b#72]
In order to improve performance, we are going to try to implement the filters in the REDUX cache instead of specific calls to the server.

**Comment by MarioP-Dev** [comment]
As we're implementing the API calls with RTK Query, the cache behavior is already defined.
React components suscribes to the data according to the hook and parameters. Once that component is unmounted, data will be deleted in 60 seconds.
In order to refetch the data from the API without unmounting the component, we should use the `refetch` function:
```
const { data, refetch } = useExampleQuery(1)
```

So, in order to implement the filters, I should work together with the "FrontEnd team" and wait until UI is updated with the filter buttons to add the functionality

**Comment by MarioP-Dev** [comment]
Nothing to do with Redux, only webapp
